# Site settings
title: TileFusion
description: Simplifying Kernel Fusion with Tile Processing
baseurl: "/TileFusion" 
url: "https://microsoft.github.io"
github_username: microsoft
mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-mml-chtml"
  tags:  "none" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - 3rd-party
  - .gitignore

# Navigation
header_pages:
  - index.md
  - examples.md
  - docs/index.md
  - benchmarks/index.md

# Just the Docs configuration
aux_links:
  "TileFusion on GitHub":
    - "//github.com/microsoft/TileFusion"
