# Site settings
mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-mml-chtml"
  tags:  "none" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Build settings
markdown: kramdown
theme: minima 

# Exclude from processing
exclude:
  - 3rd-party
  - .gitignore
