name: ruff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yapf==0.32.0 toml==0.10.2 tomli==2.0.1
        pip install ruff==0.6.5 codespell==2.3.0  
        pip install isort==5.13.2 clang-format==18.1.5
    - name: Analysing the code with ruff
      run: |
        ruff check .
    - name: Spelling check with codespell
      run: |
       codespell --toml pyproject.toml
    - name: Run isort
      run: |
        isort . --check-only
    - name: Running yapf
      run: |
        echo "please run \" yapf  --recursive .\" if errors"
        yapf --diff --recursive .
