name: ruff

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black==25.1.0
        pip install flake8==7.1.2
        pip install flake8-bugbear
        pip install flake8-comprehensions
        pip install flake8-docstrings
        pip install flake8-simplify
        pip install flake8-unused-arguments
        pip install flake8-variables-names
        pip install flake8-return
        pip install flake8-print
        pip install isort==6.0.1
        pip install mypy==1.15.0
        pip install types-setuptools types-requests types-urllib3 types-six
        pip install bandit==1.8.3
        pip install pyupgrade==3.19.1
        pip install commitizen==4.4.1
    - name: Run isort
      run: |
        isort --check-only --profile black .
    - name: Run black
      run: |
        black --check --line-length=80 .
    - name: Run flake8
      run: |
        flake8 --max-line-length=80 .
    - name: Run mypy
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs --check-untyped-defs --exclude benchmarks/ .
    - name: Run bandit
      run: |
        bandit -c pyproject.toml -r .
    - name: Run pyupgrade
      run: |
        find . -type f -name "*.py" -exec pyupgrade --py39-plus {} +
